# Generated by Django 3.2.3 on 2021-05-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20210522_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
