# Generated by Django 3.2.4 on 2021-06-16 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210522_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_img',
            field=models.ImageField(default=django.utils.timezone.now, max_length=50, upload_to=''),
            preserve_default=False,
        ),
    ]
